require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  SuggestExtensions: false
  Exclude:
    - 'tmp/**/*'
    - 'demo/templates/xml_to_class.rb'


Metrics/AbcSize:
  CountRepeatedAttributes: false

Metrics/ClassLength:
  CountAsOne:
    - array
    - hash

Metrics/MethodLength:
  Max: 15
  CountAsOne:
    - array
    - hash

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 150

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 10


