name: CI

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [ '3.2' ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up
        uses: ruby/setup-ruby@904f3fef85a9c80a3750cbe7d5159268fd5caa9f
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Rubocop Lints
        run: bundle exec rubocop -P
      - name: Run tests with ox xml serializer
        run: bundle exec rake ox_compatible_spec
      - name: Run tests with nokogiri xml serializer
        run: bundle exec rake nokogiri_compatible_spec
